# Generated by Django 4.2.25 on 2025-10-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepsky',
            name='object_name',
            field=models.CharField(db_index=True, help_text='Examples: Sirius, M31, MCG+02-60-010. See <a href="https://cds.unistra.fr/cgi-bin/Dic-Simbad" target="_blank">Dictionary of Nomenclature</a>', max_length=200),
        ),
    ]
