# Generated by Django 4.2.25 on 2025-10-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_deepsky_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_name',
            field=models.CharField(db_index=True, help_text='Examples: Sirius, Mira, HD 209458. See <a href="https://cds.unistra.fr/cgi-bin/Dic-Simbad" target="_blank">Dictionary of Nomenclature</a>', max_length=200),
        ),
    ]
